### ISSUE TITLE
"Show Toolbar" checkbox not working

### ISSUE THREAD

**Issue by ramennoodles3** [tableau/tableau-viz-lwc#100]
### Summary

Checking "show Toolbar" in the component does not show tableau toolbar

### Steps To Reproduce:

1.  Add a tableau dashboard to a lighting page and make sure that "show toolbar' is checked
1.  Load the page- the toolbar options redo/undo/revert on left and share/download etc. on right do not show up 

### Expected result

The toolbar options should display

### Actual result

Tableau dashboard displays correctly but with no toolbar

### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by illonage** [comment]
Hi @ramennoodles3 - Are you trying to embed a visualization from Tableau Online / Server or Tableau Public?

**Comment by evande0** [comment]
# Tableau _Viz_ LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau **_View_** LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information about why the Tableau **Viz** LWC is being replaced by the Tableau **View** LWC, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@ramennoodles3  If you run into issues using the new Tableau View LWC, please open a case through Salesforce.
