### ISSUE TITLE
Test class is not covering 100%

### ISSUE THREAD

**Issue by akhilkat** [tableau/tableau-viz-lwc#102]
ObjectFieldPickList apex class is only covering 93% of test coverage , 

there are two more lines which is needed to be covered , can u just please update that 

those two lines are : 
global ObjectFieldPickList(VisualEditor.DesignTimePageContext context) {
        this.rows = getRows(context.pageType, context.entityName);
    }

these two lines of code need to be covered

**Comment by evande0** [comment]
# Tableau _Viz_ LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau **_View_** LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information about why the Tableau **Viz** LWC is being replaced by the Tableau **View** LWC, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@akhilkat  If you have concerns about using the new Tableau View LWC, please open a case through Salesforce.
