### ISSUE TITLE
Custom URL from Record Field

### ISSUE THREAD

**Issue by athandra** [tableau/tableau-viz-lwc#105]
When we edit the page, the field "The URL for tableau overview" also mentions that "This property supports using an expression to define its custom label. The correct cormat is {!$label.customLabelName}."

I would like to use the URL mentioned in the record field to be visible. A different dashboard for every record. 

Can you please suggest how to link the record field with a URL to the "The URL for tableau overview"

**Comment by illonage** [comment]
Hi @athandra, 
Instead of having one unique dashboard per record, can you have a general dashboard with the data for all the records and add a filter on the record?

**Comment by rmgoodm** [comment]
I would also love a dynamic URL that I can link to a Salesforce field on the page. In my case we have a custom object where based on the contents of the record the context changes for the user requiring defaulting to a different tab of a report or different report based on the logged in user role.
