### ISSUE TITLE
Can you please add  analytics_Dashboard to targets? This allows us to use this component in the Tableau CRM Dashboards

### ISSUE THREAD

**Issue by ksengodan** [tableau/tableau-viz-lwc#107]
**What is missing from the application? Please describe.**
A clear and concise description of what the problem is. Ex. I'd like to see an implementation of [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by illonage** [comment]
Hi @ksengodan 

Thank you for opening this issue. We are working on it, we will update you in this thread once it is available.

**Comment by evande0** [comment]
# Tableau _Viz_ LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau **_View_** LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information about why this is happening, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@ksengodan  Analytics Studio uses the new Tableau **View** LWC for embedding Tableau views. The new LWC also supports embedding views published to Salesforce on lightning pages. If you have questions about using the new LWC, please open a case through Salesforce.
