### ISSUE TITLE
Tableau Viz Component not re rendering On Event

### ISSUE THREAD

**Issue by WilkinsWork** [tableau/tableau-viz-lwc#110]
This is my first leap into LWC so I suspect it is my lack of knowledge and not the component that is causing this issue.

So I looked at the youtube video which is great and tried to take the from the presentation to embed the tableau biz component into another LWC.  I have got a combo box with two different tableau URL's.  When the page opens and the combo box renders correctly and when I select one of the two values the tableau biz component picks up the url and displays the contents from our tableau instance.  Both URL's work when initially selected.  But when I then select the other url in the combo box the event fires the variable updates but the tableau component doesn't re render so it doesn't display the tableau page in the second url.  I can put a console log in to show the variable contents changing but the tableau viz component doesn't do anything.  

```js
import { LightningElement } from 'lwc';

export default class TableauVizSelector2 extends LightningElement {
    vizUrl;

    get vizOptions() {
        return [
			{ label: 'Something 1', value: 'Tableau url  here 1'},
			{ label: 'Something 2', value: 'Tableau url here 2'}
        ];
    }

    handleVizChange(event) {
        console.log('Here is the event running');
        this.vizUrl = event.detail.value;
    }
}
```

```html
<template>
    <lightning-card title="Tableau Viz Selector 2">

        <p>selected chosenValue is : {vizUrl}</p>

        <div class="slds-var-m-around_medium">
            <lightning-combobox
                label="Select a Report"
                value={vizUrl}
                placeholder="Select a Viz"
                options={vizOptions}
                onchange={handleVizChange}>
            </lightning-combobox>
        </div>

        <template if:true={vizUrl}>
            <c-tableau-Viz viz-url={vizUrl} height="500"></c-tableau-Viz>
        </template>

    </lightning-card>
</template>
```

I have also the same example where I am retrieving the contents of the combobox from custom meta data types but again when I change the selected value in the combo box the vizUrl value changes correctly but the component doesn't re render.

Again this is my first real LWC so I assume I have missed something or don't understand something correctly.

Any help be greatly appreciated.

Thanks

Paul

**Comment by NewtoLWC** [comment]
I'm having the same issue. Looks the re-render is not working!

**Comment by pozil** [comment]
Hi @NewtoLWC I'm not on the Tableau team but I took the time to do a PR that should address this.
I've made the changes so that they would go in the Spring '22 release.

**Comment by evande0** [comment]
# Tableau Viz LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau View LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@NewtoLWC Similar functionality can be achieved with the new Tableau View LWC by using the Tabs component. Each tab can contain a different Tableau View LWC embedding content from different URLs. Switching between tabs will load the Tableau View LWC as expected.
