### ISSUE TITLE
Filtering based on mapping fields

### ISSUE THREAD

**Issue by franciscoaponte** [tableau/tableau-viz-lwc#111]
Hello,

We have many embedded Tableau dashboards that are working great, thank you for your work on this component. We are having issues with filtering on a record page though.  We have a fairly complex Viz that has a column called SFDC ID, we are trying to filter that with Contact Id, but have had no luck.  Is there any additional documentation on how to ensure we are building this in Tableau to ensure it filters? The readme info is useful and it is what I followed, but I think the issue is on the Tableau Viz side, and not sure how to proceed.

Thank you for all your work on this again! It is a very valuable component for us an has enabled some quick wins for our users!

**Comment by illonage** [comment]
Hi @franciscoaponte,

Thank you for reaching out. 

Some follow-up questions: Can you check that the field is called SFDC ID when you are editing the workbook and was not renamed? Is the field on the dashboard or viz that you are embedding? 

Thanks,
Gigi

**Comment by illonage** [comment]
@franciscoaponte Did you solve this issue? Can we close this issue?

**Comment by evande0** [comment]
# Tableau Viz LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau View LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

> We have a fairly complex Viz that has a column called SFDC ID, we are trying to filter that with Contact Id, but have had no luck. 

@franciscoaponte The Advanced Filtering should work as long as `Contact Id` is selected from the Salesforce filter dropdown, and the Tableau filter name is an exact match for the column name in the data source. Another option is to rename `SFDC ID` to `Contact ID` and use the Filter on Record checkbox. If you run into issues using the new Tableau View LWC, please file a bug through Salesforce.
