### ISSUE TITLE
Viz component not populating on Home Page

### ISSUE THREAD

**Issue by karthikkasala** [tableau/tableau-viz-lwc#112]
### Viz component not populating on Home Page

_After installing the component in our full sandbox and providing the "share" URL, it ends up showing up as a blank box and then not at all on the home page itself_.

### Steps To Reproduce:

1.  Add component to page.
2. Input URL
3. Adjust height to 1000. 
4. Save and check activation
5. Go to actual home page
6. See nothing. 

### Expected result

_Should see component with embedded URL in page_.

### Actual result

_Nothing_.

### Additional information

![blank box - tableau viz connector](https://user-images.githubusercontent.com/48218106/140992727-3183de84-fdb4-47ae-9168-531dbc73d8ac.png)

**Comment by karthikkasala** [comment]
Please delete this issue. Will create new one.

**Comment by illonage** [comment]
Hi @karthikkasala,

Thank you for opening this issue.

Can you confirm that the URL that you copied & pasted looks like: _https://us-east-1.online.tableau.com/t/gigisite/views/PythonExample/Seattle911?:showAppBanner=false&:display_count=n&:showVizHome=n&:origin=viz_share_link_

Can you open the developer console when accessing the page and take a screenshot, please? You can find the instructions [here](https://developer.chrome.com/docs/devtools/open/) on how to do it on Google Chrome.

Thanks,
Gigi

**Comment by karthikkasala** [comment]
Following up. Do you want me to just inspect the area where the component should be and screenshot that or something else? Thanks.

**Comment by illonage** [comment]
@karthikkasala if you can right-click on the page > Inspect  and open the tab called 'console' and share a screenshot here that would be great.

**Comment by evande0** [comment]
# Tableau Viz LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau View LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@karthikkasala If you encounter problems using the new Tableau View LWC, please file a bug through Salesforce.
