### ISSUE TITLE
Viz Component doesn't rendering properly

### ISSUE THREAD

**Issue by tzewdei** [tableau/tableau-viz-lwc#113]
After installing the managed package in the sandbox and adding the share URL , the component display as horizontal line and doesn't display the contents.

**Steps to reproduce the issue**
1. Install the managed package
2. add the component into the Ltng page
3. Add the URL
4. Save the changes 
5. Activate the component
6. Go back to the page
7. See only horizontal lines

**Expected Result**
The component should display with the shared URL Content in the page

**Actual Result** 
Nothing

**Comment by evande0** [comment]
# Tableau Viz LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau View LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@tzewdei Please try using the new Tableau View LWC, which is part of the Standard Components list and does not need to be installed.
