### ISSUE TITLE
Tableau Viz - Additional Filter is not working - Salesforce Integration

### ISSUE THREAD

**Issue by PKansaraBain** [tableau/tableau-viz-lwc#118]
### Summary
Tableau Visualization is returning no data if Additional Filter is added

We have integrated Tableau Visualization to our Account Flexipage. It is working fine without filter and we are able to see the Tableau dashboard on Account Page as well.

Now we have to add filter based on one field, As soon as we apply filter It's coming as blank.

I have debug the LWC and the issue with setting up value for "advancedFilterValue" (tableauViz.js - GetRecords Method)

### Steps To Reproduce:

1.  Add all the Components from the Master branch of this Repo (Master Branch)
1.  Added the WrapperTableauViz to the Flexipage
1.  Added Additional Filter
![image](https://user-images.githubusercontent.com/87303778/151967290-689197c2-4211-421d-be6d-6b2a8a72fcfd.png)

### Expected result
Dashboard Should shown the filter data

### Actual result
Showing Blank

### Additional information
Below is the Screenshot of Tableau Viz LWC from our Repo :
![image](https://user-images.githubusercontent.com/87303778/151967406-b4bb8fa5-3e07-411a-8c9a-ed4b37e24dec.png)

**Comment by evande0** [comment]
# Tableau Viz LWC is being Archived
All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau View LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).
For more information, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@PKansaraBain The new Tableau View LWC supports dynamic filtering via Advanced Filters. By checking the box, the view will be filtered on the `[RecordType] ID`. For example, `Account ID`. The Advanced Filter fields can be used to dynamically filter on another record field.
