### ISSUE TITLE
Report column width not dynamic, hiding column values

### ISSUE THREAD

**Issue by itssanmitra** [tableau/tableau-viz-lwc#121]
Hi,
We are implementing Tableau LWC for detail record page in Salesforce. We are displaying a Tableau report. Issue we are facing is the column width set in Tableau is getting messed up in Salesforce view and values are displaying as #### due to less column width. How this can be fixed? Even if we change the layout of the flexi page in Salesforce to have the Tableau component capture the full width, still the report columns are not flexed. Kindly guide.

Thanks,
Sanhita

**Comment by evande0** [comment]
# Tableau Viz LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau View LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm). 

For more information, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@itssanmitra Unfortunately, the Tableau View LWC simply embeds the viz as it was authored and can't alter the column width. If having the LWC occupy the full width of the viewing area doesn't fix the issue, the viz itself might need to be redesigned to accommodate smaller form factors. 

Please see https://community.tableau.com/s/question/0D54T00000xRrGpSAK/fit-width-or-automatic-size-doesnt-resize-my-column-size-within-a-table-when-a-different-resolution-is-selected
