### ISSUE TITLE
Dropdown Filters stopped working

### ISSUE THREAD

**Issue by plarsS3** [tableau/tableau-viz-lwc#124]
### Summary

Prior to last week, dropdown filters worked just fine and now filters are not showing values.  You can use arrows on the filter to switch, but the dropdown won't render.  This has been tested on several clients, browsers, etc.

### Steps To Reproduce:

1.  Navigate to embedded Tableau visualization
2.  Select dropdown filter

### Expected result

List of values presented

### Actual result

No list is displayed

### Additional information
![image](https://user-images.githubusercontent.com/105309674/167684867-2a092e75-2870-41b1-9e7c-f625aa0054db.png)

![2022-05-10 11_55_38-Advanced Analytics _ Salesforce](https://user-images.githubusercontent.com/105309674/167684751-397f8f44-9afe-49dc-8b3a-b7abb12084ac.png)

**Comment by illonage** [comment]
Hi @plarsS3 - Can you confirm that you are using the component from AppExchange? Which version of Tableau are you using?

**Comment by plarsS3** [comment]
Hi Gerladine,

Yes, we are using the component from the app exchange API v. 48.  I went yesterday to see if there was an update or anything, but it all seems to be up to date.    Thank you for your insight.

***@***.***

**Comment by illonage** [comment]
Does it work now?

**Comment by illonage** [comment]
No, which version of Tableau and Salesforce are you using?

**Comment by temlov** [comment]
Hi. I am facing the same issue so maybe I can chip in what I found out so far. The drop down menus are working in my client's Salesforce Staging org but not in Production org. In Production org it does not work with Tableau Online nor Server.

From Salesforce Audit Trail I could see there was a change in production org: "Organization setup action: lockerServiceNextOffOn has changed." just before these drop downs stopped working. In Salesforce documentation this was mentioned for Summer '17 release so not sure why would it change now and if related to the problem.

**Comment by plarsS3** [comment]
Thank you for your insight. I have found that the dropdowns work in the client's sandbox as well, just not production.

To make it more perplexing, I checked in another production org and they do work there. But both orgs are the same version.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by evande0** [comment]
# Tableau Viz LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau View LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm). 

For more information, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@plarsS3 Recent validation shows this works with the new Tableau View LWC. If you run into issues using the new LWC, please file a bug report through Salesforce.
