### ISSUE TITLE
Seamless authentication in Azure AD IdP

### ISSUE THREAD

**Issue by mbossanwest** [tableau/tableau-viz-lwc#127]
**What is missing from the application?**
When using SFDC and Tableau with Azure AD IdP, the user login SFDC will get a pop up to authenticate with Tableau.

**Describe the solution you'd like**
We would like a seamless authentication for end user to not have to login in both SFDc and Tableau pop-up.

**Describe alternatives you've considered**
Can you enable Trusted ticket authentication maybe ? or any other solution.

**Additional context**
We are seriously considering moving away from Tableau.

**Comment by evande0** [comment]
# Tableau Viz LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau View LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm). 

For more information, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@mbossanwest  Good news! The new Tableau View LWC supports token authentication to Tableau, eliminating the need to sign into Tableau once you've authenticated to Salesforce.
