### ISSUE TITLE
Request to pass parameters to Tableau Server from Salesforce

### ISSUE THREAD

**Issue by marsam11** [tableau/tableau-viz-lwc#129]
**What is missing from the application? Please describe.**
Pass the current Salesforce object record to Tableau Server as a parameter instead of a filter

**Describe the solution you'd like**
If we were able to pass a parameter through we wouldn't need to build large extract tables that contain all accounts in our Salesforce environment. We'd be able to leverage live connections that leverage the parameter to reduce the query times and limit storage space.

**Describe alternatives you've considered**
Currently we have to build a large daily extract for Tableau Server to ingest that meets the specific criteria of the visualization in question because we need the performance of the viz to return results within seconds.

**Additional context**
We have worked through SAML SSO already and got it to work in our SSO/Okta Salesforce environment

**Comment by evande0** [comment]
# Tableau Viz LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau View LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm). 

For more information, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@marsam11 Unfortunately, Tableau LWCs (including the new native Tableau View LWC) leverage the Tableau Embedding API which does not support accepting parameters to return to Tableau. It only supports filtering a viz based on specific field names.
