### ISSUE TITLE
Advance filter not working in tableau visualisation web component in salesforce

### ISSUE THREAD

**Issue by AafaqueH8793** [tableau/tableau-viz-lwc#130]
Advance filter not working in tableau visualisation web component in salesforce

**Comment by anyoung-tableau** [comment]
Please provide repro steps and additional details on what exactly isn't working, including any error messages you may be encountering.

**Comment by illonage** [comment]
Be sure that the field is on the visualization and that you didn't make any typo issues when entering the field name, it should match the name in the datasource.

**Comment by evande0** [comment]
# Tableau Viz LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau View LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm). 

For more information, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)
