### ISSUE TITLE
Embed Tableau Viz in Salesforce using LWC - Okta SSO

### ISSUE THREAD

**Issue by PankajSiteMinder** [tableau/tableau-viz-lwc#131]
Hello All,

1. The need is to embed Tableau server dashboard in Salesforce using Tableau LWC(Lightning web component) and use SSO if user has already signed in to Salesforce (Seamless authentication) .
2. Both Salesforce and Tableau server uses the same Okta IdP.
3. As per [documentation](https://help.tableau.com/current/server/en-us/saml_config_LWC.htm) we have enabled 'in-frame authentication on Tableau Server' using the TSM commands & also we have enabled 'Enable IFrame embedding' at Okta side. Still at Saslesforce side we are able to see Sign In with Okta page in the iframe as shown in image below and not able to get SSO based Seamless authentication experience even if user is signed in with Okta beforehand. 
<img width="943" alt="Screenshot 2022-10-31 105500" src="https://user-images.githubusercontent.com/99863232/198939550-da6445af-0edc-4451-a59e-886877d94e60.png">

What step are we missing? Can anyone please help on this?

**Comment by evande0** [comment]
# Tableau Viz LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau View LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm). 

For more information, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@PankajSiteMinder The new Tableau View LWC supports token authentication which removes the need to set up SSO. Instead, the Salesforce Org is registered as an external authorization server on your Tableau site (aka, Connected Apps OAuth 2.0), and Salesforce mints JWTs that are used to authenticate you to Tableau every time you load the Tableau LWC.
