### ISSUE TITLE
Tableau Viz Lightning Web Component

### ISSUE THREAD

**Issue by AnilGithub12** [tableau/tableau-viz-lwc#142]
We are trying to use Tableau Viz Lightning Web Component which is been downloaded from App Exchange. We are trying to show Tableau dashboard within Salesforce with the help of this package which isn't working. Need help to understand what is the blocker and how can we fix it. while login in to SF through SSO and meeting all the requirement of how to show dashboard in SF however no luck. Can we setup a call to go through this. Contact Email - anil.vakkalanka@toshibagcs.com

**Comment by evande0** [comment]
# Tableau Viz LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau View LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm). 

For more information, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@AnilGithub12  If you encounter trouble migrating to the new Tableau View LWC, please file a bug report through Salesforce.
