### ISSUE TITLE
Issue when accessing Tableau from Mobile

### ISSUE THREAD

**Issue by miguelsonmi** [tableau/tableau-viz-lwc#146]
Hello,

When we try to access Tableau from the LWC on mobile, we are redirected to a blank page. We get the same error both when we try to sign in from SSO or Tableau ID.

From desktop, everything works fine.

Any idea on what could cause the issue?

Thank you very much for your help.

**Comment by evande0** [comment]
# Tableau Viz LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau View LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm). 

For more information, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@miguelsonmi The native Tableau View LWC that is replacing this project works on iOS and Android using the Salesforce Mobile app, but not on mobile browsers.
