### ISSUE TITLE
Tableau LWC Isn't Working on Mobile or Tablet

### ISSUE THREAD

**Issue by kimmoutes** [tableau/tableau-viz-lwc#150]
### Summary

Hello,

When we try to access Tableau from the LWC on mobile, we are redirected to a blank page. From desktop, everything works fine.

### Steps To Reproduce:

1. Using Salesforce on mobile or tablet
2. Go to the Contact page where the LWC is embedded
3. Click on the tab that houses the LWC
4. We are taken to a blank screen

### Expected result

We should have taken to the tableau report

### Actual result

We were taken to a blank screen

### Additional information
Does this LWC only work on desktop? Any help you can provide is much appreciated! 
Kim

**Comment by evande0** [comment]
# Tableau Viz LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau View LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm). 

For more information, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@kimmoutes The native Tableau View LWC that is replacing this project works on iOS and Android using the Salesforce Mobile app, but not on mobile browsers.
