### ISSUE TITLE
Adding Filtering for Global Variables for App Pages, Communities and maybe Objects

### ISSUE THREAD

**Issue by tcufrogger** [tableau/tableau-viz-lwc#18]
So currently the LWC as designed will only show filter options when used inside 
a Salesforce Object.  This approach is sound and makes a lot of sense given how Salesforce leverages Standard Controllers on Objects.  There is a different type of filtering we can do inside of Salesforce called a Global Variable.  There are a number of Global Variables available but the ones related to $User are the ones that will provide the additional value.  So two examples.  

1. A customer has developed a Dashboard that is around Pipeline and other key metrics and they want to use the LWC to embed this on the Home Page of the Sales App.  Since the Home Page is just a Lightning App Page there is no Standard Controller to leverage but there is the global variable {!$User.FullName) that could be passed to Tableau to be able to filter the viz to just the User that is logged in.  

2. A customer is using the LWC to embed Tableau Content on a Salesforce Community but wants to filter the view of the Dashboard to the Company of the user that is logged in.  Using {!$User.CompanyName) we can look up the Company name of the current logged in user and pass that value to Tableau.  

In theory we could do something on the Tableau side with RLS since the user is authenticated on both sides but this is simple and takes away the need for managing a complex RLS table/workflow on the Tableau side.

I am sure there are other ideas of filtering especially on the Community Cloud side I have not consider that should be explored (such as using Custom Metadata values or declared APEX) but a quick win it would seem would be to enable the support for Global Variables.

If it was possible to simply in the ad hoc filter field add $User.FullName rather than Owner.Id or Account.Name maybe if the LWC code is picking up the {!xxxxx} wrapper then all a Global Variable is {!$xxxx}.

https://developer.salesforce.com/docs/atlas.en-us.pages.meta/pages/pages_variables_global_user.htm

**Comment by illonage** [comment]
After discussions, Lightning Web Component doesn't support Global Variables
