### ISSUE TITLE
Quick Actions  and passing values from the LWC

### ISSUE THREAD

**Issue by tcufrogger** [tableau/tableau-viz-lwc#19]
I think this enhancement is a bit more complex but maybe someone at Salesforce has some insight.  Now that we have a LWC is it possible to capture a value off a viz and pass it from the LWC to some other action or LWC.  So several examples ...

1. A user is looking at a viz and much like inside of EA we want to call quick actions such as open a task, update a opportunity, add a lead, etc ...  EA calls this the Action Framework and basically it is just passing a selected value from the LWC to call a quick action in Salesforce.  In one Dealer360 demo we mocked up the idea was a Salesforce user was looking at a KPI dashboards of their dealers they manage and they quickly wanted to select a Dealer in the Viz and have a list of actions including plan a visit that would open as quick actions in Salesforce.  All we would need to do is to be able to call the action and pass the Account ID for example.

2. Next example would be combining a List View in Salesforce with a Tableau Viz.  This would be a situation where maybe I am looking at a Service Dashboard and my different ticket counts by priority  Although I can have an interactive dashboard that would have a table in Tableau, one option might be that I want to pass a value out of the LWC and have that create the Salesforce List View under the Tableau LWC as a way to have more options for interaction.

3. The final example is centered around an App page or Home page.  In this use case there is a Tableau Dashboard that is taking advantage of some of our geospatial features and have a number of different insights.  Clicking on an object or value would send the value out of the LWC so that one LWC could drive showing an Einstein Predictions LWC object to the left.  Below that we have the twitter feed LWC and we want to update that with some values that would serve as a Hashtag Search.  Maybe there is another Tableau LWC where a value gets passed and a filtered dashboard loads.  There are all sorts of options this might open up - passing data to Salesforce Maps to generate a route, creating a list view of accounts or users, driving a Action Menu so the user can click some buttons to start some actions ... 

If this is possible - this allows the visual aspect of Tableau to be the source for other LWC's in an App or Page ...

**Comment by evande0** [comment]
# Tableau Viz LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. For more information, [please see the README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@tcufrogger Please open a Team Dependency or reach out to the internal Eureka slack channel if you'd like to discuss this in more detail.
