### ISSUE TITLE
Use of Custom Metadata and RestAPI

### ISSUE THREAD

**Issue by tcufrogger** [tableau/tableau-viz-lwc#20]
In the current orgs I set up I have created a custom Metadata Type for Tableau.  This contains the Server Name, Site path (if there is one such as Tableau Online), Site Name (Not really needed but I added it just in case), Personal Access Token Name and Personal Access Token Secret.

![image](https://user-images.githubusercontent.com/32880478/80526981-48851f80-8959-11ea-8d42-a2616e7b6f78.png)

In addition I have created a APEX Class to allow me to call it in all my VisualForce Pages

```
public class xTabHelperController {
    public Tableau__mdt metadata { get; set; }
    public xTabHelperController(ApexPages.StandardController controller) {
        metadata = [
            SELECT
                Server_Name__c,
                Site_Root__c,
                Token_Secret__c,
                Token_Name__c,
                Site_Name__c
            FROM Tableau__mdt
            WHERE DeveloperName = 'Base'
            LIMIT 1
        ];
    }
}
```

Where I find this helpful and other customers might as well is when I create a VisualForce page with the embedded URL I can call the server/site from the Metadata so as long as my content is named the same on every server I do not have to touch every VF page.  This would be helpful to customers who use a Dev Tableau Server and a Scratch Org/Sandbox/Dev Org where they want to test their code and then promote it to Production.  The code stays the same - just the metadata values are different.

We have also started using the Metadata values with Personal Access Tokens so we can Sync users between Salesforce and in this case Tableau Online (Both are using SF Identity).  With PAT's we have just started scratching the surface of what we can do.  

For the LWC I could see two items.  One is if I had a check box that said leverage Tableau Metadata values when I could paste the Share URL with the Metadata Values into the LWC and as I promoted the code to other orgs or in my case install SF packages with the code ready I would not have to copy and past every URL over and over again with the correct server/site paths.

Here is an example of how I use it in VF so you get the idea ..

```
<apex:page standardcontroller="Account" extensions="xTabHelperController" docType="html-5.0" lightningStylesheets="true">
<script>
window.location= ("https://{!metadata.Server_Name__c}/{!metadata.Site_Root__c}/views/OppEmbed/DiscountHistory?Id={!Account.Id}&?iframeSizedToWindow=true&:embed=y&:toolbar=no&:showAppBanner=false&:showShareOptions=false&:display_count=no&:showVizHome=no#5");
</script>
</apex:page>
```

The other enhancement on the LWC would be to use the Metadata and PAT to use the RestAPI to create a list of possible dashboards/sheets to embed without the need to copy and paste the URL.  

I don't think you make the Metadata as a requirement so if you want to copy and paste a Tableau Public URL or another URL from another Tableau Server.  It would be nice to toggle it on per use if there is a Custom Metadata record and have something that does not hard code the server and site paths.

**Comment by evande0** [comment]
# Tableau _Viz_ LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau **_View_** LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information about why the Tableau **Viz** LWC is being replaced by the Tableau **View** LWC, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@tcufrogger I tend to agree with @pozil 's assessment of this enhancement raised on #47 

>That would be great indeed but to be transparent, the cost of this would not the same as this PR.
>
>We would need to authenticate with Tableau in the Salesforce backend before querying Tableau APIs for the fields (I don't know much about this part). This means that we would need to store credentials on the Salesforce side among other configuration details. It would require some significant changes to the component's architecture.

If you still think this is a worthwhile addition, please feel free to reach out on the internal Eureka slack channel or open a Team Dependency.
