### ISSUE TITLE
Problem rendering dashboard from Tableau Online in Salesforce mobile app

### ISSUE THREAD

**Issue by lzachary** [tableau/tableau-viz-lwc#27]
It is not possible to view a dashboard in Tableau Online from in Salesforce Mobile. 

### Steps To Reproduce:

1. Use LWC to embed a dashboard from Tableau Online into Salesforce
2. Use the phone preview in Salesforce. This succeeds when the mobile form factor is enabled (see other bug).
3. Go to the Salesforce org in the Salesforce app on your mobile device
4. On the mobile app navigate to the page with the LWC embedded.
5. Log on when prompted to Tableau Online
6. You will then see redirects happening a couple times but are not able to select viewing the dashboard in Tableau Mobile
 7. You end up landing on a blank page.

### Expected result

You are able to see the dashboard embedded in the Salesforce mobile app.

### Actual result

You see a blank page where the dashboard should be.

### Additional information

![mobile error](https://user-images.githubusercontent.com/41013658/82486606-20e22c80-9aab-11ea-9167-e69a180463a9.jpg)

**Comment by Skinbert** [comment]
I can confirm that this also happens on a cloud based Tableau Server, not exclusive to Tableau Online.

**Comment by hayleystevens** [comment]
I ran into this issue when SSO was not set up correctly. Once I fixed SSO and updated settings in Tableau Online to the following, I was able to access Tableau dashboard within Salesforce mobile 

![image](https://user-images.githubusercontent.com/46764059/98272837-68b81b80-1f46-11eb-98ac-95e3bcc552fb.png)

**Comment by jutamind** [comment]
Tried the embedding options that you've proposed above but still the Tableau Viz component couldnt load the dashboard in Salesforce mobile apps. Got the error as follow: [https://ibb.co/tmWcdWq](url)

> I ran into this issue when SSO was not set up correctly. Once I fixed SSO and updated settings in Tableau Online to the following, I was able to access Tableau dashboard within Salesforce mobile
> 
> ![image](https://user-images.githubusercontent.com/46764059/98272837-68b81b80-1f46-11eb-98ac-95e3bcc552fb.png)

**Comment by illonage** [comment]
Hi @jutamind - Which IdP are you using?

**Comment by jutamind** [comment]
Azure AD

**Comment by illonage** [comment]
Thank you for your quick answer. Microsoft has blocked all in-frame authentication and it cannot be enabled. Instead, Microsoft only supports pop-up authentication in a second window. As a result, the Mobile App is not going to work. The workaround for the moment is to use Sparkler: https://kb.tableau.com/articles/Issue/tableau-viz-lightning-web-component-does-not-work-on-salesforce-classic?_ga=2.262602188.1376070805.1610407075-1522774385.1608684711&_fsi=NoOuGy5v

**Comment by jutamind** [comment]
@illonage , so are you saying that we use Tableau Viz component for desktop view and Sparkler for mobile view, ie 2 components to be added to expose 1 dashboard to the users? If so, how do i filter the component visibility so that Sparkler component is only viewable on mobile view and vice versa?

**Comment by illonage** [comment]
@jutamind sorry for the confusion. You should use Sparkler for mobile and desktop for now.

**Comment by SamarthaJanney** [comment]
Hello @illonage ,

1. The need is to embed Tableau server dashboard in Salesforce using Tableau LWC(Lightning web component) and use SSO if user has already signed in to Salesforce (Seamless authentication) .
2. Both Salesforce and Tableau server uses the same Okta IdP.
2. We are able to view the Tableau Server Sign-in page after embedding the dashboard URL using Tableau LWC. When we click on the sign-in button, popup will open trying to authenticate and close automatically then redirects back to the same sign-in page.
3. What step are we missing?
4. Do we need to enable iframe (in-frame authentication) in Tableau Server as well as in Okta ?
Help us out in enabling a seamless navigation between Salesforce and Tableau Server.
Identity Provider : OKTA
Tableau Server - 2018.1 and OKTA SAML Enabled
Salesforce - OKTA SAML Enabled

**Comment by illonage** [comment]
Hi @SamarthaJanney,

In which browser are you experiencing that? You need to enable iframe authentication in Okta 
<img width="506" alt="Screen Shot 2021-03-19 at 3 28 15 PM" src="https://user-images.githubusercontent.com/7159287/111848694-f0d10900-88c8-11eb-9308-0c3fe5c573a7.png">

Also in Tableau Server: https://kb.tableau.com/articles/howto/embedding-tableau-server-dashboards-into-a-website-without-prompting-for-credentials

I hope it helps,
Gigi

**Comment by rahulagg144** [comment]
@lzachary I am facing the same issue where I see a blank screen on Salesforce mobile app where I should see the Tableau dashboard. It works well on chrome on desktop. Were you able to resolve this or implement any workaround of any sorts to make it work?

**Comment by rahulagg144** [comment]
Resolution - https://help.salesforce.com/articleView?id=sf.branded_apps_cross_site_tracking.htm&type=5

**Comment by evande0** [comment]
# Tableau _Viz_ LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau **_View_** LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information about why the Tableau **Viz** LWC is being replaced by the Tableau **View** LWC, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

Hi all, fortunately the new Tableau View LWC with seamless auth unlocks most Salesforce mobile app scenarios by allowing the component to authenticate to Tableau using JWTs. This obviates the need to allow in-frame authentication. If you run into issues using the new Tableau View LWC, please open a case through Salesforce.
