### ISSUE TITLE
Custom labels for user-facing labels and messages

### ISSUE THREAD

**Issue by muenzpraeger** [tableau/tableau-viz-lwc#31]
**What is missing from the application? Please describe.**
Currently the component contains hard-coded string values in English for all user-facing labels/messages, which doesn’t make it really international friendly.

**Describe the solution you'd like**
Instead of hard-coded strings custom labels should be leveraged. Ideally a set of the most common languages should be shipped as default.

**Comment by evande0** [comment]
# Tableau _Viz_ LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau **_View_** LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information about why the Tableau **Viz** LWC is being replaced by the Tableau **View** LWC, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@muenzpraeger  The good news is that the new Tableau View LWC does support localized strings so this should no longer be an issue. If you run into issues using the new Tableau View LWC, please open a case through Salesforce.
