### ISSUE TITLE
"Session Expired" after login

### ISSUE THREAD

**Issue by hey-look-its-tim-dries** [tableau/tableau-viz-lwc#51]
Hi,

Embedding public dashboard works like a charm.

But embedding Tableau Server dashboards gives me a "session expired" right after logging in.

![Schermafbeelding 2020-06-22 om 13 23 02](https://user-images.githubusercontent.com/37512908/85282868-be56c480-b48c-11ea-94c4-a20c83c76598.png)

Kind Regards,
Tim Dries

**Comment by illonage** [comment]
Hi Tim, 
Thank you for trying the Tableau Viz LWC. Which method of authentication are you using on your Tableau Server? And which version of Tableau Server do you use?

**Comment by illonage** [comment]
@hey-look-its-tim-dries any update?

**Comment by hey-look-its-tim-dries** [comment]
**Hi illonage,**

We had a LOCAL authentification with username and pw on oour server.

Having said that, I just tried to reproduce the time-out error and I could not anymore.
Works like a charm now.

I'll come back to this tread when I encounter this error again.

Thanks for the tight follow up.

**Cheers,
Tim Dries**

**Comment by illonage** [comment]
Hi @hey-look-its-tim-dries - Thank you for your answer. I will close this issue. Feel free to re-open it if you encounter it again. Gigi
