### ISSUE TITLE
LWC Small dashboard sizing

### ISSUE THREAD

**Issue by Skinbert** [tableau/tableau-viz-lwc#54]
I am trying to add small dashboards into certain Salesforce records pages which shows well however on closer inspection I am seeing a scroll bar (very small and faint) on the right hand side. 

I have a 100 tall high dashboard in a 110 height LWC box, Dashboard set to Entire view.

I believe this issue exists when using Sparkler so would like confirmation if this can be rectified.

![LWC slider](https://user-images.githubusercontent.com/15361822/85570633-6b674380-b62b-11ea-80a6-79baf1e443c5.png)

**Comment by tcufrogger** [comment]
This is something you can fix on the Tableau side.  First make sure unless you need it that you delete the mobile view of your dashboard.   Several releases ago we added auto create of the mobile view to Tableau and more than likely based on your small pixel size Tableau is trying to serve up the mobile view and not the default view.  In addition, when working with dashboards this small you should consider using a range for size where the smallest size is the size you want to scale down is the min and the max is not set.  This will allow the viz to 'grow' for users with more pixels to display.

Also - this looks like a Sheet and not a dashboard.  Although Sheets can be embedded, if you drop the sheet into a dashboard you have more control of sizing.  Hope this helps!

**Comment by Skinbert** [comment]
Thanks for the quick response,

This was a dashboard, but your recommendation to remove the mobile version pretty much fixed it straight away.

Great to know for the future and thank you for the quick response

Alastair Young


Alastair Young
InterWorks | Analytics Lead
t: +44 (0)203 137 22 33  |  
m: +44 (0)7729 858 760
www.interworks.com
Unit 1, Christchurch Business Park, Dorset, BH23 4FL
Co Reg No. 08368863  |  VAT 154881290
2019 Tableau Partner of the Year UK & Ireland

**Comment by illonage** [comment]
Hi @Skinbert,
Thank you for participating in the Beta program. 
I am glad that it is working for you now. If you are setting the height to be inferior to 500, it is Tableau's normal behaviour to pick up the mobile version of your dashboard.
