### ISSUE TITLE
Advanced Filtering does not work

### ISSUE THREAD

**Issue by BenRoche** [tableau/tableau-viz-lwc#55]
### Summary

We have embedded the LWC on our Account page and use the advanced filtering to pass a parameter to the tableau dashboard, the parameter is passed properly from account in the correct tableau filter, but the filter is not applied. The dashboard remains empty.

### Steps To Reproduce:

1.  Add the LWC to account page and specify the Viz URL
2.  Check Filter visualization based on the page
3. Specify the filters and save
4. Open the Account page

### Expected result

The LWC displays the visualization pre-filtered on the account (parameter used in filter)

### Actual result

The visualization filter is populated with the correct parameter (account Number) but the visualization does not register it.
When we search in the filter for that exact same account number and select it the visualization works.
We tried

**Comment by illonage** [comment]
Hi @BenRoche,

I am the PM for the Tableau Viz LWC.

Would it possible to send me an email at gzanolli@tableau.com, please? I would like to set up some time with you to go over this issue.

**Comment by BenRoche** [comment]
All good, thx for the help
