### ISSUE TITLE
Authentication Types 

### ISSUE THREAD

**Issue by Skinbert** [tableau/tableau-viz-lwc#60]
Hi,

As per Alpha, We have set up our testing arena using Okta SAML.  2 questions on this,

1. Is this still the case for Beta following Tims response?  Is this a SAML authentication Component only?
&
2. If so, Is this ever likely to develop any further to replace the Sparkler connected App?

Thanks
Alastair

**Comment by illonage** [comment]
Hi @Skinbert, 
If you want SSO for Tableau Online/Server, we support only SAML authentication. Our goal is to totally replace Sparkler. Which authentication method are you using?
