### ISSUE TITLE
Additional salesforce field filter mapping is not working for me

### ISSUE THREAD

**Issue by ShalakaSP** [tableau/tableau-viz-lwc#74]
### Summary

I am trying to embed Tableau Dashboard in company record Page.
But when I am trying to apply additional filters Tableau dashboard is not displaying filtered data.

**### Steps To Reproduce:**
1. Embed dashboard at company Record Page like this: 
![image](https://user-images.githubusercontent.com/75437466/101051379-6d76ec00-3553-11eb-9443-335b8b25e440.png)

This is how we have configured:
![image](https://user-images.githubusercontent.com/75437466/101051749-d1011980-3553-11eb-945a-69ad5f41ddc3.png)
Here we are trying to match Salesforce Persistent ID field with Tableau MDM Persistant Id

2. But if i go to salesforce Record Tableau dashboard is not filtered according to Persistent ID:

This is the salesforce Company Record with persistent ID:
![image](https://user-images.githubusercontent.com/75437466/101052382-8af88580-3554-11eb-9cbb-5a741490cb86.png)

**Actual Result:**

Dashboard is still displaying like this:
![image](https://user-images.githubusercontent.com/75437466/101052550-c2ffc880-3554-11eb-8f08-945a281de7dc.png)

**### Expected result**
it should display like this:
![image](https://user-images.githubusercontent.com/75437466/101052650-e296f100-3554-11eb-8c81-c64231654ab8.png)

**Additional Information:**
On Company Object Persistent Id is external ID:

![image](https://user-images.githubusercontent.com/75437466/101052866-1e31bb00-3555-11eb-9fe4-3d954f6edecd.png)

Please let me know if you need anything from my side.

**Comment by illonage** [comment]
Hi @ShalakaSP - Thank you for the details. 
I have a couple of additional questions:
- Do you have any custom views set up on the Tableau dashboard?
- When you are in Salesforce, can you open the Developer console, and look for "data visualization? Can you share with the URL after src, please? It should look like that: https://us-west-2a.online.tableau.com/t/gzanollisf/views/LinkedInSalesNavigatorDashboard/SalesActivitybyTeamType?%3AshowAppBanner=false&%3Adisplay_count=n&%3AshowVizHome=n&%3Aorigin=viz_share_link&%3Asize=1177%2C700&:embed=y&:showVizHome=n&:tabs=n&:toolbar=n&:apiID=host1

![Uploading Screen Shot 2020-12-03 at 1.02.30 PM.png…]()

**Comment by ShalakaSP** [comment]
Sorry to say but i am not aware of Data Visualization Option in Developer
Console.
Can you please guide me what exactly you are looking for?


if you looking for Tableau Dashboard URL :
Here it is:

https://cfgtableauqa/t/BusinessServicesAnalyticsandReporting/views/Customer360FinalVersionv4/Dashboard/N101633@corp.internal.citizensbank.com/1f8766cd-ca0e-4141-9605-ceda6b28cf85?:display_count=n&:showVizHome=n&:origin=viz_share_link



Thanks & Regards,
Shalaka Pagar
+1(484) 682-6895

**Comment by illonage** [comment]
I have created a gif below to walk through the steps to get the embedded URL. Thanks

![2020-12-03_16-36-22 (2)](https://user-images.githubusercontent.com/7159287/101107122-7af99980-3586-11eb-9a4e-d96e74e5c746.gif)

**Comment by ShalakaSP** [comment]
I got it. Thank you very much for the Gif.
Here is the URL :
:
https://cfgtableauqa/t/BusinessServicesAnalyticsandReporting/views/Customer360FinalVersionv4/Dashboard/N101633@corp.internal.citizensbank.com/1f8766cd-ca0e-4141-9605-ceda6b28cf85?%3Adisplay_count=n&%3AshowVizHome=n&%3Aorigin=viz_share_link&%3Asize=962%2C800&MDM+Persistant+Id=547121954614995302&:embed=y&:showVizHome=n&:apiID=host1



Thanks & Regards,
Shalaka Pagar
+1(484) 682-6895

**Comment by illonage** [comment]
Thank you for sharing the URL. The URL structure seems correct, you can actually see that we are passing the right filter **MDM+Persistant+Id=547121954614995302**.

What happens if you open the URL in a different browser tab? Can also check if you have any [custom view](https://help.tableau.com/current/pro/desktop/en-us/customview.htm) set up on Tableau, please?

**Comment by ShalakaSP** [comment]
Hi Geraldine,

if i open the URL in the new tab it displays the default view not filtered
view.
I don't think so there are any Custom View set up on the Tableau Dashboard.
Please find attached screenshot for custom view and Dashboard default view.





Thanks & Regards,
Shalaka Pagar
+1(484) 682-6895

**Comment by illonage** [comment]
Hi - I cannot see the screenshot. Can you send me an email at gzanolli@tableau.com, please? I can schedule a quick call.

**Comment by ShalakaSP** [comment]
Issue is resolved:

I was using wrong field from Tableau Dashboard so please make sure you are using right fields from Tableau Dashboard.


Thank You
Shalaka
