### ISSUE TITLE
Context filtering for Tableau Viz Lightning component on home page

### ISSUE THREAD

**Issue by jutamind** [tableau/tableau-viz-lwc#77]
**What is missing from the application? Please describe.**
To support context filtering based on userid for Tableau Viz Lightning component added to Salesforce home page

**Describe the solution you'd like**
Allowing the component to filter based on userid will allow the component to be added to home page and display user related Tableau KPI dashboard/report

**Describe alternatives you've considered**
None

**Additional context**

**Comment by illonage** [comment]
Hi @jutamind,

Thank you for your feedback. We recommend setting it up SSO and using [Tableau Row Level Security](https://help.tableau.com/current/pro/desktop/en-us/publish_userfilters.htm) to filter the dashboard based on the userid. It is the most secure way to do it. 

Let us know if you've any questions

**Comment by jutamind** [comment]
@illonage, my idea is to create a reusable single KPI Tableau dashboard to be embedded on SFDC home page and pass the SFDC user ID to this dashboard so that the records relevant to the userid is filtered when the dashboard gets loaded when the user login to SFDC.

If I understand correctly, if we set row level security in Tableau dashboard, then we will need to create different dashboard for different sales rep. If this is the case, this is not feasible maintenance wise and too cumbersome. Correct me if I have the wrong understanding on route level security in Tableau dashboard

**Comment by illonage** [comment]
Using row-level security, you need only one dashboard for all your sales rep. You publish one dashboard with a user-based filter. The sales rep A has access to California only, they are going to be only the sales in California, Sales rep B can access only Washington, he is going to access the same dashboard but they are going to see only sales in Washington. 

You can read more about the Best Practices for Row Level Security with Entitlements Tables [here](https://www.tableau.com/learn/whitepapers/row-level-security-entitlements-tables).

I hope it helps,
Gigi

**Comment by jutamind** [comment]
@illonage If I want to create a KPI Tableau dashboard for all sales reps reporting on revenue and quantity by product group for all sales region but by sales rep, so when sales rep A login to SFDC, he will see only see his records and KPI and vice versa for sales rep B. Can this be done using row levels security as well?

**Comment by tagyoureit** [comment]
@jutamind it can be done. I recommend checking out this great [Tableau and Behold](https://tableauandbehold.com) blog or any of the other resources that dive in depth into RLS.

**Comment by illonage** [comment]
@jutamind let us know if you have additional questions.
