### ISSUE TITLE
Embed Tableau Viz in Salesforce using LWC - SSO Issue

### ISSUE THREAD

**Issue by SamarthaJanney** [tableau/tableau-viz-lwc#78]
Hello All,

1. The need is to embed Tableau server dashboard in Salesforce using Tableau LWC(Lightning web component) and use SSO if user has already signed in to Salesforce (Seamless authentication) .
2. Both Salesforce and Tableau server uses the same Okta IdP.
3. We are able to view the Tableau Server Sign-in page after embedding the dashboard URL using Tableau LWC. When we click on the sign-in button, popup will open trying to authenticate and close automatically then redirects back to the same sign-in page.
4. What step are we missing?
5. Do we need to enable iframe (in-frame authentication) in Tableau Server as well as in Okta ?

Help us out in enabling a seamless navigation between Salesforce and Tableau Server.
Identity Provider : OKTA
Tableau Server - 2018.1 and OKTA SAML Enabled
Salesforce - OKTA SAML Enabled

**Comment by illonage** [comment]
Hi @SamarthaJanney, 
Can you check on Tableau Server if you have "Authenticate using an inline frame" selected, please? It is Under Settings > Authentication > Embedding. Did you also enable [IFrame embedding](https://help.okta.com/en/prod/Content/Topics/Settings/settings-customization-general.htm?_fsi=NoOuGy5v) in Okta?

Cheers,
Gigi

**Comment by SamarthaJanney** [comment]
Hello @illonage,
Thank you for your quick response. We are trying this suggestion as a scheduled maintenance we are awaiting approvals! We will update you the results shortly! 

Thanks,
Samartha

**Comment by illonage** [comment]
@SamarthaJanney any update on this issue? Can we close it?

**Comment by SamarthaJanney** [comment]
Hello @illonage ,
Sorry for the delay. Due to technical issues within our systems, the process is taking time to test.
Please go ahead and close the loop. We will update our final results once we complete the process.

Thanks,
Samartha

**Comment by SamarthaJanney** [comment]
Hello @illonage ,
As previously discussed please find the latest update on resolving the issue:

Issue was resolved after upgrading Tableau server to 2020.3. Currently we are able to embed Tableau views into Salesforce and it is working without an issues. We have not enabled Iframe in both Okta and Tableau due to security concerns. So we are using pop-up authentication currently and users are able to click on sign-in button and it automatically authenticates the user.

Thank you so much for all your help.

Thanks,
Samartha

**Comment by illonage** [comment]
Thank you Samartha
