### ISSUE TITLE
Site-SAML using Tableau Server with Salesforce IDP

### ISSUE THREAD

**Issue by Skinbert** [tableau/tableau-viz-lwc#80]
I have been working on this problem for a number of days without much progress.

I am receiving 'refused to connect' errors when trying to connect with the dashboard in question which has been set up with Site SAML using Salesforce as the IDP. I am getting inconsistent results when testing the connection. When I upload the metadata file I do not get any assistance with the Assertion Name. If I select NameID it will connect correctly, but moments later will fail. 

I have added the URL to the CSP Trusted Sites, I have selected the clickjacking options within the session settings also as it is still throwing a "in a frame because it set 'X-Frame-Options' to 'sameorigin'." error also.

Is there any documentation available around this?  Is Site SAML on Tableau Server possible? or any settings not documented?

Additionally, I have set up Single Sign on settings in Salesforce. Is this still required when using Site SAML?  Could this be an issue.

Any help would be appreciated.
Thanks
Alastair Young

**Comment by illonage** [comment]
Hi @Skinbert,

We have a lot of documentation online for your use case: 
- https://help.tableau.com/current/pro/desktop/en-us/embed_ex_lwc.htm
- https://help.tableau.com/current/server/en-us/saml_config_LWC.htm
- Configure Site-Specific SAML: https://help.tableau.com/current/server/en-us/saml_site_specific.htm
- Configure SSO from Salesforce to Tableau: https://help.salesforce.com/articleView?id=sf.identity_provider_examples_tableau_online.htm&type=5&_ga=2.175876068.770906257.1611592648-2038885535.1599606405&_fsi=gBl8Zaz9

It looks like you have a difficult time mapping Salesforce users to Tableau. I recommend reading this article below:

- Map Salesforce Users to the SAML Service Provider: https://help.salesforce.com/articleView?id=sf.service_provider_map_users.htm&type=5&_ga=2.175876068.770906257.1611592648-2038885535.1599606405&_fsi=gBl8Zaz9

If you are still having issues, can you share screenshots or recording so we can help you better?

Thanks,
Gigi

**Comment by Skinbert** [comment]
Hi Gigi,

Thank you for your response. I have reverted my test server back to server wide SAML and all this works fine.

When I enable to the Site-SAML, I get the following.
[cid:image001.png@01D6F966.01D7D230]

I have looked at the vizportal logs, I receive this line
called API method has parameter of IAuthenticatedUser type, but when called there was no logged in user. Responding with 'InvalidSessionException'.
I have not made many significant changes when moving to Site Enabled SAML, aside from the requirements detailed in the documentation with the Entity Id, ACS and the corresponding Start URL requirement but still to no avail.

As far as I can see, Salesforce is not initialising the login part of the single sign on and is expecting it to be done manually.

Happy to share more information privately.

Thanks
Alastair






Alastair Young
InterWorks | Analytics Lead
t: +44 (0)203 137 22 33  |  
m: +44 (0)77 2985 8760
www.interworks.com
Unit 1, Christchurch Business Park, Dorset, BH23 4FL
Co Reg No. 08368863  |  VAT 154881290

**Comment by illonage** [comment]
Hi Alastair - Unfortunately, I cannot see the screenshot that you shared. If you can email it to me with more information that would be great thanks.

**Comment by dtreskunov** [comment]
Hi Alastair, while I don't have any experience with Tableau Lightning Web Component, it sounds like the issue you are seeing is because one of the web servers (Salesforce, Tableau Server, or Tableau Server samlservice) is sending a `X-Frame-Options: sameorigin` header and the browser is refusing to render the content if it is embedded in an iframe served by another web server.

Can you clarify which HTTP request (in the browser Developer Tools) is failing due to this issue?

Have you tried enabling the other option on the Tableau Server site Authentication settings page, under Embedding Options?

![image](https://user-images.githubusercontent.com/3477960/106965948-4e363f80-66f9-11eb-958a-ac6c119954bf.png)

**Comment by illonage** [comment]
Hi @Skinbert - Any update? Can we close the issue?

**Comment by Skinbert** [comment]
@illonage 
Apologies for the delay. This ticket can now be closed.  The issue lies in some of the Tableau Server settings which is awaiting a fix by the dev team I believe. 

Some chrome flags were also blocking them, I am going to try and document all this for future reference

**Comment by illonage** [comment]
@Skinbert, thank you, I am going to close this issue. It would be awesome if you could share the issue and the Tableau version that you have for future references.
