### ISSUE TITLE
No Longer able to Use Expressions in URL

### ISSUE THREAD

**Issue by tom-barad-natixis** [tableau/tableau-viz-lwc#81]
### Summary

I installed package in our sandbox on 1/14/2021. When I installed in production yesterday (2/4/2021), a key feature - the ability to use expressions (custom labels) in the URL for the viz - no longer works.

### Steps To Reproduce:

1.  Install package in new Salesforce org
1.  Add Tableau Viz LWC to a Lightning page (record, app, any)
1. On URL configuration, attempt to use an expression in the URL ([!Lable.CustomLableName}

### Expected result

LWC should take URL with expression as a valid entry

### Actual result

Receive error message saying that expressions are not allowed and to remove them.  Also, in hover text over information icon, there is no mention of using expressions.

### Additional information

Installed in sandbox on 1/14/2021 and this functionality was allowed and worked like a charm with expressions.
When installed on 2/4/2021 in production, the new error message (see actual result) appears; hover text no longer mentions expressions.

Sandbox (1/14 installation):
![image](https://user-images.githubusercontent.com/78599040/107034569-df062d00-6784-11eb-83c8-282e35d18372.png)

Production (2/4 installation)
![image](https://user-images.githubusercontent.com/78599040/107034743-22f93200-6785-11eb-8f7f-e335ed517236.png)

Version 1.2, same publish date.

We are using Tableau Server

**Comment by illonage** [comment]
Hi Tom,

Thank you for reaching out.

It might be a permission issue. Do you have the same set of permissions in the sandbox and production? 
Can you also check if you are on the same Salesforce version in your sandbox and production? If yes, does it still work in your sandbox?

Thanks,
Gigi

**Comment by tom-barad-natixis** [comment]
Hi Gigi -

I do have the same permissions in all orgs (System Admin), but you were right in having me check the SF version.  In our full sandbox, which has been updated to v51, we have the ability to use expressions.  In v50 (prod and our dev sandboxes), it is not available.  

I found this in the Release Notes for Spring 21 (v51):
https://help.salesforce.com/articleView?id=release-notes.rn_forcecom_lab_expressions_in_comp_labels.htm&type=5&release=230

Can you confirm this is probably the culprit?

Thanks,
Tom

**Comment by illonage** [comment]
Yes, you should wait for your production environment to be updated to v51.
Thanks,
