### ISSUE TITLE
Advanced Salesforce field filter is not persistent for multiple Tableau dashboard tabs

### ISSUE THREAD

**Issue by anhhhh** [tableau/tableau-viz-lwc#82]
### Summary

Our team is embedding a Tableau dashboard into the Salesforce Account page layout. This dashboard consists of five tabs. Two tabs don't show data filtered properly and instead have visuals that show all aggregate numbers, which is not the expected behavior. 

After looking at the instructions in [this closed issue](https://github.com/tableau/tableau-viz-lwc/issues/74), I took a closer look at our embedded URL structure and found that:
- When the filter structure has the plus sign in it (i.e. customer+uuid=123456789), the visuals are filtered correctly.
- Clicking on a different tab changes the original URL structure (i.e. customer%2Buuid=123456789), then the visual filter stops working and shows the aggregate amount. If I manually change this back to the previous format (customer+uuid), then it works again.

### Steps To Reproduce:

1. From the Salesforce Account page, follow the [gif instructions](https://user-images.githubusercontent.com/7159287/101107122-7af99980-3586-11eb-9a4e-d96e74e5c746.gif) to extract the embedded URL 
2. Click on the fourth or fifth tab of the dashboard and verify the numbers showing up in the visuals.

### Expected result

The numbers in all visuals should show data from a specific customer.

### Actual result

The numbers in some visuals on the fourth/fifth tab show data from all customers.

**Comment by illonage** [comment]
Hi @anhhhh, thank you for submitting this issue. I was able to reproduce your experience, the team is going to investigate it.

**Comment by illonage** [comment]
@anhhhh, we were not able to reproduce this step: "Clicking on a different tab changes the original URL structure (i.e. customer%2Buuid=123456789), then the visual filter stops working and shows the aggregate amount."

Would you be able to share a video/recording? You can also reach out directly by email: gzanolli@tableau.com if you don't want to share the information publically.

**Comment by illonage** [comment]
hi @anhhhh - When you are setting filters in the component, we are using URL parameters filters. Switching tabs triggers an AJAX request rather than a full page load, URL filters are not loaded. You can revive your workbook to filter based on parameters as explained [here](https://kb.tableau.com/articles/issue/url-parameter-filter-ineffective-when-switching-between-tabs).

I hope it helps,
Gigi

**Comment by anhhhh** [comment]
Hi Gigi, thanks for your suggestion and for sharing the KB article. Let me check back with my team and we'll reach out soon to schedule a call with you. Thanks again!
