### ISSUE TITLE
Context filtering not working

### ISSUE THREAD

**Issue by sjtorre16** [tableau/tableau-viz-lwc#83]
### Summary
i'm unable to get the record context filtering working. I have the Tableau field name mapped to the Salesforce field name and the embedded report actually calls out the name in the drop down menu but doesn't display the Tableau report data in SF.

### Steps To Reproduce:

1. The Salesforce Account object we have a Tableau report is named "Account Trends' that I've added to the Account Lightning record page. 
2. The Account names field in the Tableau report is named 'Carrier' and I have 'Account Name' as the 1 to 1 mapped Salesforce field. 
3. The drop down for this field 'Carrier' actually shows the proper Account name in this 'Carrier' drop down list however no data is displayed on the report embedded on the Account record page in Salesforce. 
4. If I click that 'Carrier' field the account name initially displayed (filtered) is not checked. 
5. If I manually check it or apply no filters at all the Tableau report display the report data embedded into the SF Account page without issue

### Expected result

The selected Carrier (Account Name) should be checked in addition to displayed so that I can see the data

### Actual Result
The selected Carrier (Account Name) is displayed on the SF Accounts drilled into however value is not checked and therefore entire Tableau report data does not display (only tableau filter label values).

**Comment by illonage** [comment]
Hi @sjtorre16 - Could you share a screenshot of how you configured the Tableau Viz Lightning web component, please?

**Comment by sjtorre16** [comment]
Hi Illonage,

Sure, please see attached.
![SS1](https://user-images.githubusercontent.com/79225014/108366035-e5a19500-71c5-11eb-99b4-d941a1a2dd9e.PNG)

**Comment by illonage** [comment]
Thank you @sjtorre16 for sharing. Your configuration seems correct, could you check on the Tableau side that Carrier is the right field name in your Tableau data source?

Can you also check the URL as explained in this gif: https://user-images.githubusercontent.com/7159287/101107122-7af99980-3586-11eb-9a4e-d96e74e5c746.gif, please?

**Comment by sjtorre16** [comment]
Sure, FYI I have marked out our domain due to security concerns.  Please see attached

Thanks,

Samson
![DVCapture2](https://user-images.githubusercontent.com/79225014/108718825-d9327a80-74ec-11eb-8096-7f1bf42c7f9b.PNG)

**Comment by illonage** [comment]
Hi @sjtorre16 - thanks again for sharing the screenshot, but I am missing a part of the URL. Can you try to click on the URL and open it in a new tab, please? Is your visualization filtered? Did you check on your Tableau Server the underlying data? 
<img width="460" alt="Screen Shot 2021-02-22 at 10 47 04 AM" src="https://user-images.githubusercontent.com/7159287/108754841-51a03800-74fb-11eb-84e4-bbbe8e137c02.png">

**Comment by sjtorre16** [comment]
Hi Gigi,

I just have a 'viewer' license in Tableau so if I opt to open the 'data vis' URL in another browsing tab, I just get the broken report displayed within the full screen of the new browsing tab session.

**Comment by illonage** [comment]
Can you email me gzanolli@tableau.com, and we can set up a time to go over the issue? It would be useful to ask for a creator or explorer license for the call or have someone that has the rights on the call for debugging.

**Comment by sjtorre16** [comment]
Sure, let me work on getting my Tableau license upgraded and I would be more than happy to email you and work with you.  
Thank you so much!! :-)

**Comment by sjtorre16** [comment]
Thanks Gigi, I have a 'creator' license now in Tableau and just emailed you.  Looking forward to working with you and thanks so much for your willingness to assist! :)

-Samson

**Comment by sjtorre16** [comment]
Thanks again working with me Gigi to discover that the case sensitivity and Tableau filtering was affecting the context filtering in the SF Tableau Viz Lightning component add-in.  I'll work with my Tableau Admin with regards to your recommendations.

-Samson
