### ISSUE TITLE
The Tableau Viz component doesn't show in the Lightning app builder page

### ISSUE THREAD

**Issue by Nicolas-vrcc** [tableau/tableau-viz-lwc#84]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  Install the Tableau Viz Component with an admin account
2. Go to a Lightning app builder page

### Expected result

It should display in the component list

### Actual result

It doesn't.

### Additional information

See picture.
<img width="159" alt="Capture d’écran 2021-02-24 à 18 51 58" src="https://user-images.githubusercontent.com/25429456/109043403-9aa9e500-76d1-11eb-9bb8-d83c8b6ec7ca.png">

**Comment by illonage** [comment]
Hi @Nicolas-vrcc - You need to deploy your domain as explained [here](https://help.salesforce.com/articleView?id=sf.domain_name_testing_and_rollout.htm&type=5) to be able to use custom components in your Salesforce org

**Comment by illonage** [comment]
Hi @Nicolas-vrcc 
Any update? Can we close the issue?
