### ISSUE TITLE
Issues with in frame authentication for Tableau LWC using OneLogin IDP

### ISSUE THREAD

**Issue by anhhhh** [tableau/tableau-viz-lwc#85]
We currently have pop-up authentication for the Tableau LWC and want to enable a seamless user authentication experience as our org has OneLogin SSO enabled for both Salesforce and Tableau Server even prior to our efforts of Tableau - Salesforce integration. We followed these two documentation links ([this](https://kb.tableau.com/articles/howto/embedding-tableau-server-dashboards-into-a-website-without-prompting-for-credentials) and [this](https://kb.tableau.com/articles/issue/embedded-dashboard-displays-a-login-prompt-but[…]tion?_ga=2.193639460.84118724.1614606872-372048816.1607662848)) but it was still unsuccessful. Below is the screenshot of the login issue users see in Salesforce: 
![image](https://user-images.githubusercontent.com/12240471/110814342-5aad3b00-8257-11eb-8cae-b8079085c025.png)

On the OneLogin side, we chose to allow framing from the following origins: https://acme.lightning.force.com/ and https://tableau.analytics.acme.org. Question: Are both Tableau and Salesforce origins needed to enable in frame auth or only one of them? 
![image](https://user-images.githubusercontent.com/12240471/110813285-5cc2ca00-8256-11eb-8c7c-316fe443dfa8.png)

On the Tableau side, we followed this instruction: 
For Server-Wide SAML
Open a command prompt as an Administrator on the computer where Tableau Server is installed
Execute the following commands:
```
tsm configuration set –k wgserver.saml.iframed_idp.enabled -v true
tsm pending-changes apply
tsm restart
```

Questions: Is there anything else you think we might have missed in our configurations? Can you recommend a way to troubleshoot this issue?

Thanks so much.

**Comment by illonage** [comment]
Hi @anhhhh,
Please find my answers below:

**- Are both Tableau and Salesforce origins needed to enable in frame auth or only one of them?**
On the OneLogin side, you need to allow framing from the Salesforce org URL only: https://acme.lightning.force.com.

**- Is there anything else you think we might have missed in our configurations? Can you recommend a way to troubleshoot this issue?**
Multiple options that might resolve the problem:
             - Ensure that the user accessing the view has their authentication type set to SAML.
             - Could you check if you have iFrame embedding enable at the site level: Go to Settings > Authentification: Select                          Enable an additional authentication method, select SAML, and then select Edit connection and scroll down to embedding options and select Authenticate using an inline frame

Let me know if it is working 
Gigi

**Comment by anhhhh** [comment]
@illonage just to confirm, below are the steps to be done in Tableau, correct?

> - Ensure that the user accessing the view has their authentication type set to SAML.
> - Could you check if you have iFrame embedding enable at the site level: Go to Settings > Authentification: Select Enable an additional authentication method, select SAML, and then select Edit connection and scroll down to embedding options and select Authenticate using an inline frame

**Comment by illonage** [comment]
For this step "Ensure that the user accessing the view has their authentication type set to SAML.", you can check both on the Salesforce and Tableau side. The second step is only on the Tableau side

**Comment by anhhhh** [comment]
@illonage thank you for clarifying! Will check with my team to make changes and circle back.

**Comment by anhhhh** [comment]
@illonage For this point, we can confirm that SAML is enabled for all users on both Salesforce & Tableau

> - Ensure that the user accessing the view has their authentication type set to SAML.

With the next step, we original saw this suggestion on Tableau doc for Tableau Online:

> - Could you check if you have iFrame embedding enable at the site level: Go to Settings > Authentification: Select Enable an additional authentication method, select SAML, and then select Edit connection and scroll down to embedding options and select Authenticate using an inline frame

The issue is our Tableau admin can't see these options on Tableau Server as there is no Authentication tab for them (see screenshot below)
![image](https://user-images.githubusercontent.com/12240471/111675116-273c5480-87f3-11eb-9b3c-1869b9058472.png)

Is it possible for us to get on a screensharing call with you to look at our Tableau server setup? We're based in both EST and PKT time zones, so it may be challenging to coordinate, but we would really appreciate your support here.

**Comment by LGraber** [comment]
Can you open the developer console in Chrome (looks like Chrome) and check a couple of things. First look in the console output and see what it says. My guess is something like cant be displayed because X-Frame-Options set to deny or sameorigin. If not, I am curious what it says. If says that, it means you have not enabled AllowFraming on OneLogin. If you are getting a different error, then it could be that you setup the safelist incorreclty You need to put the SF domain in the list of places to allow framing. If you look at the response from Ping in the network trace, you should see a header that looks like Content-Security-Policy: frame-ancestors <>. That is where you shold see the SF domain that you are embedding in. Let me know what you see. Thanks!

**Comment by anhhhh** [comment]
@LGraber - I did see the error message below among a dozen other ones - not sure how relevant the others are but can show you on a call.

> Refused to display 'https://edx.onelogin.com/' in a frame because it set 'X-Frame-Options' to 'deny'

In terms of the OneLogin setup, we added 3 domain origins to the framing protection setting: 
https://acme.my.salesforce.com 
https://acme.lightning.force.com
https://acme--c.documentforce.com

Is there anything else we're missing?

WRT to the below, I'm not sure I follow your instruction entirely. Can we get on a call and you show me how to?

> You need to put the SF domain in the list of places to allow framing. If you look at the response from Ping in the network trace, you should see a header that looks like Content-Security-Policy: frame-ancestors <>. That is where you shold see the SF domain that you are embedding in. 

Thank you!

**Comment by illonage** [comment]
<img width="1123" alt="Screen Shot 2021-03-19 at 2 43 22 PM" src="https://user-images.githubusercontent.com/7159287/111845104-7650bb00-88c1-11eb-83ed-e437826b79ce.png">
Can you confirm that you checked "Allow framing from the following origins" in Onelogin?

**Comment by anhhhh** [comment]
@illonage yes, that is correct.

**Comment by illonage** [comment]
<img width="1112" alt="Screen Shot 2021-03-19 at 3 10 38 PM" src="https://user-images.githubusercontent.com/7159287/111847040-44415800-88c5-11eb-946b-5739e62159ea.png">
I just tested with my account, the issue might come from the second check-box. Can you select "Fall back to allowing ALL framing in those browsers (less secure)" and try again please?

**Comment by michaeljfitzgerald** [comment]
@anhhhh Did you get this to work within OneLogin?

**Comment by anhhhh** [comment]
@michaeljfitzgerald - not yet, our OneLogin admin is still evaluating the impact of that option "Fall back to allowing ALL framing in those browsers (less secure)". Do you have any references or materials that can speak to the risk of such? thank you!

**Comment by michaeljfitzgerald** [comment]
Yeah, doesn’t seem aligned to security best practices to just fall back to be wide open. Just thinking out loud but it may be because there are more domains than just the 3 you mentioned in allow listing. Maybe you can capture the network traffic to see the switching across all of the domains. 

I also recently learned that Salesforce is coming out with enhanced domains on March 31. I’m not sure if that helps with all of the different sub domains but it seems like it may standardize them but not sure.

**Comment by illonage** [comment]
We contacted OneLogin support and they came back with this answer on why "Allow framing from the following origins" is not working: 
"I did some research and found that the "Allow framing from the following origins" setting currently only applies to the Admin console and not the login page.
The settings should apply elsewhere (login page) but support for it has not been implemented consistently, so there is a mix, but practically application to admin seems to be where it is successfully implemented.

So, you may also select "Allow all framing regardless of origin (DEPRECATED, please migrate to origin whitelists below)" and it should work."

**Comment by anhhhh** [comment]
@illonage Thank you for the follow-up! Our IT admin is still assessing the option "Allow all framing...". In the meantime, we revert to "Disallow all framing" but the error "edx.onelogin.com refused to connect" still persists. Any advice on how we could get back to the pop-up user auth method? :( 

@michaeljfitzgerald -  to your point re: capturing other domains, someone earlier in this thread told me to look at "Ping in the network trace, you should see a header that looks like Content-Security-Policy: frame-ancestors <>". However, I wasn't able to follow that instruction to the T. Do you have a suggestion on how to do so?

**Comment by anhhhh** [comment]
I waited till the next business day and still got the "onelogin refused to connect" error. Are there settings from Tableau Server we need to revert as well? Last time our Tableau admin ran these commands:

```
tsm configuration set –k wgserver.saml.iframed_idp.enabled -v true
tsm pending-changes apply
tsm restart
```

**Comment by anhhhh** [comment]
`tsm configuration set –k wgserver.saml.iframed_idp.disabled -v true`

would this work to reset Tableau Server?

**Comment by anhhhh** [comment]
@illonage can you please help review the command line above or point me to the right direction? thank you!

**Comment by illonage** [comment]
@anhhhh Try: `tsm configuration set –k wgserver.saml.iframed_idp.enabled -v false`

**Comment by ashish413a** [comment]
@illonage  @anhhhh  - We have similar issue, we whitelisted the SF domain in OneLogin, no luck, did we ever resolve this issue, if yes, can you point to the resolution?

**Comment by evande0** [comment]
# Tableau _Viz_ LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau **_View_** LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information about why the Tableau **Viz** LWC is being replaced by the Tableau **View** LWC, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@anhhhh @ashish413a It's possible that the new Tableau View LWC with seamless authentication will address the login concerns you have. If you run into issues using the new Tableau View LWC with seamless auth, please open a case through Salesforce.
