### ISSUE TITLE
Safari "Prevent Cross-Site Tracking" with SAML

### ISSUE THREAD

**Issue by tom-barad-natixis** [tableau/tableau-viz-lwc#86]
Hi all -

In Safari, we had to disable the security feature called "Prevent Cross-Site Tracking" in order to get SSO/SAML to work.  Without this, a "page expired" message appears.  This affects both the desktop and mobile versions of Safari.  

In Chrome on desktop, we are fine (but Chrome on iPad doesn't play well with LEX).  The SF Mobile app works fine as well.

Just checking in to see if this is something that you can address with code or if this is something that Apple requires.

We are using Ping as our IdP with Tableau Server.

Thanks -
Tom

**Comment by illonage** [comment]
Hi Tom - It is indeed something that Apple requires. After Salesforce releases Spring 21, users need to change their settings for the component to work on Safari. Thanks

**Comment by evande0** [comment]
# Tableau _Viz_ LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau **_View_** LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information about why the Tableau **Viz** LWC is being replaced by the Tableau **View** LWC, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@tom-barad-natixis It's worth noting that this is still required for the new Tableau View LWC. Relatedly, using Tableau View LWC on mobile requires enabling cross-site tracking for the Salesforce Mobile app. If you run into issues using the new Tableau View LWC, please open a case through Salesforce.
