### ISSUE TITLE
Mobile App will not work on ADFS and Azure AD IdP.

### ISSUE THREAD

**Issue by alixohrt** [tableau/tableau-viz-lwc#87]
Reading through the documentation here:
https://help.tableau.com/current/online/en-us/saml_config_TOL_LWC.htm

It's noted that the mobile app is currently not supported with Azure AD as the IdP. Are there any suggested work around to use this on the mobile application? Is this due to a limitation with Azure AD or a limitation of the Salesforce Mobile App?

**Comment by illonage** [comment]
Hi @alixohrt 
This is due to a limitation with Azure AD, Microsoft blocks all in-frame authentication, and the Salesforce Mobile App requires in-frame authentication. Currently, the only workaround is to use Sparkler: https://kb.tableau.com/articles/Issue/tableau-viz-lightning-web-component-does-not-work-on-salesforce-classic?_ga=2.179051949.801399895.1614620986-1522774385.1608684711&_fsi=NoOuGy5v.

Sparkler Integration works for the Classic UI and Lightning. 

Thanks,
GG

**Comment by Skinbert** [comment]
@illonage 
Just for clarification - The Lightning Web Component will work using Azure AD on the desktop?  But not on mobile from what I understand from this thread. Is this correct?

Or does Azure show a pop up window then authenticating even in Desktop.

**Comment by illonage** [comment]
@Skinbert if Azure AD is set up, you will see a login button and the end-user is going to need to click on the button, but they don't have to authenticate on Desktop.

**Comment by Skinbert** [comment]
Hi @illonage 
Thank You.  Would you have a screenshot of how this would look?
So essentially they will see a sign on button in the Viz area, click it, and the dashboard will display. Still no requirement to enter password?

Appreciate your response

**Comment by illonage** [comment]
Hi @Skinbert Thank you for your patience, I totally missed your answer. It would look the screenshot below:
![image](https://user-images.githubusercontent.com/7159287/124036100-55186400-d9b2-11eb-8443-bf0be2020955.png)
No requirement to enter your password on Desktop.

**Comment by evande0** [comment]
# Tableau _Viz_ LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau **_View_** LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information about why the Tableau **Viz** LWC is being replaced by the Tableau **View** LWC, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@alixohrt @Skinbert The new Tableau **View** LWC supports seamless authentication using JWTs, obviating the need for in-frame authentication in the Salesforce Mobile App. There are more details in the [Tableau **_View_** LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm) documentation. If you run into issues using the component, please open a case through Salesforce.
