### ISSUE TITLE
Hook for dynamic URL 

### ISSUE THREAD

**Issue by rmgoodm** [tableau/tableau-viz-lwc#89]
enhancement idea

In many cases per account we will have 2 or 3 tableau reports with multiple tabs. It would be very useful for the URL to be configurable as a Salesforce field so we can let the Salesforce record (formula field) set what page is displayed on load. Better yet when  another lightning control changes the URL without page refresh. The idea of dynamically changing the URL will allow for more content available to our end users to dig and explore right where they work in Salesforce.

**Comment by evande0** [comment]
# Tableau _Viz_ LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau **_View_** LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information about why the Tableau **Viz** LWC is being replaced by the Tableau **View** LWC, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@rmgoodm The new Tableau View LWC supports dynamic filtering on Record pages based on that record's fields. Perhaps more helpful to your described scenario is the [Tabs LWC](https://www.lightningdesignsystem.com/components/tabs/). This enables you to design a single page with multiple vizzes for users to explore.  If you run into issues using the new Tableau View LWC, please open a case through Salesforce.
