### ISSUE TITLE
Dynamic Filtering on Tasks

### ISSUE THREAD

**Issue by AndrewLewisIPFS** [tableau/tableau-viz-lwc#94]
I have a use-case where we want to embed on the Task record page using a dynamic filter for the Account ID. I've tried using custom label merge fields mapping to the related ID against Tableau's reference field. The only time this works is when the ID is hard-coded into the URL. We can't use the additional filter system that allows us to reference Tableau fields with record fields because the Task object is not supported with the UI API used to create that reference. 

Is there something I'm missing, or is this a use-case that the visualization doesn't support yet due to the SF limitation on UI API with Task object?

**Comment by illonage** [comment]
Hi @AndrewLewisIPFS - Can you share more information, please? You should be able to see in the UI the "Advanced Filter". Did you try to enter the information there? 
![Screen Shot 2021-04-29 at 2 07 23 PM](https://user-images.githubusercontent.com/7159287/116618687-3afbd000-a8f4-11eb-9069-56904ed5f219.png)

**Comment by illonage** [comment]
@AndrewLewisIPFS do you still need help? Can we close this issue?

**Comment by AndrewLewisIPFS** [comment]
Yes, go ahead and close the issue. My problem was just due to lack of understanding how the component supported and the way custom labels work with it. I've figured it out, though!


Andrew Lewis

Salesforce Administrator



Imperial PFS

301 W. 11th Street

Kansas City, MO 64105

Phone: 816-507-7896 | Work: 816-260-7409

***@***.******@***.***> |  ipfs.com<http://www.premiumfinance.com/>

________________________________

**Comment by illonage** [comment]
Let us know if you have any feedback on how we can improve your experience 😄
