### ISSUE TITLE
Issue : Embedding tableau-viz-lwc Component into Aura Component and passing modified Tableau URl

### ISSUE THREAD

**Issue by ashisht1988** [tableau/tableau-viz-lwc#95]
I have requirement to pass some application Id to the tableau Server for Filtration Purpose.
I have installed tableau-viz-lwc Managed Package  and calling tableau-viz-lwc component component from Aura Component.
On load of Aura Component fetching respective application id using Aura Init Handler 
appending the fetched Id's into tableau URL and same URL Passing into tableau-viz-lwc componnet.

### Expected result

Based on the Parameter which I have appended into URL ,Dashboard should be rendered

### Actual result

Parameter send for Filtration is ignored .if I will refresh the page multiple times then it loads correctly.

Can you please help where is the issue.

**Comment by evande0** [comment]
# Tableau _Viz_ LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau **_View_** LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information about why the Tableau **Viz** LWC is being replaced by the Tableau **View** LWC, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@ashisht1988 The new Tableau View LWC supports Custom Query Parameters for static filtering. E.g., `Region=West`. Dynamic filtering is available on Record Pages using Advanced Filters. If you run into issues using the new Tableau View LWC, please open a case through Salesforce.
