### ISSUE TITLE
New Feature: Trusted Ticket Authentication

### ISSUE THREAD

**Issue by mbossanwest** [tableau/tableau-viz-lwc#99]
**What is missing from the application? Please describe.**
SSO is not working for all organization. For example Microsoft has blocked all in-frame authentication and it cannot be enabled.
It result in a poor user experience with a Tableau Sign-in page (although user is already signed in salesforce.com).

**Describe the solution you'd like**
The LWC is really great, easy to setup, easy to use and provide a good user experience.
What we would need is to be able to choose the authentication option by either SSO or Trusted Ticket.

**Describe alternatives you've considered**
We are using third party web app Sparkler (https://kb.tableau.com/articles/issue/tableau-viz-lightning-web-component-does-not-work-on-salesforce-classic)  that is providing level of integration we need. But with one more web app to maintain and a poor front-end UX integration (border on the iframe, no auto resize).

**Comment by Kovner** [comment]
Thank you for the feedback. We definitely realize that we don't have all of the authentication options that people need for the LWC. Trusted Authentication is a great tool for a lot of reasons but it is also limited for a lot of options and so we don't plan on making it work with the LWC. But we have a much better token-based authentication feature that we are working on that we believe will solve your scenario. Is it early in development, so we don't have a timeline. 
Thanks again for the feedback!

**Comment by mbossanwest** [comment]
@Kovner , do you have any news on the token-based authentication feature you mentioned above ?
Today, we are still using sparkler but it is not supported app and therefore become obsolete and open to vulnerability.

**Comment by pozil** [comment]
Sorry @mbossanwest, no update on my part, this is with the Tableau team.
Perhaps @illonage can chime in?

**Comment by zzFluke** [comment]
@Kovner thanks for the updated on this ticket. I wonder about token-based auth you mentioned, has it been added and may I ask for any documentation reference please.

**Comment by LGraber** [comment]
We are trying to release support for this. It is still a top priority for the team

**Comment by evande0** [comment]
# Tableau _Viz_ LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau **_View_** LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information about why the Tableau **Viz** LWC is being replaced by the Tableau **View** LWC, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@mbossanwest The new [Tableau View LWC supports seamless authentication](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm) using JWTs. Setting this up eliminates the need for users to login to Tableau after they have authenticated to Salesforce. If you run into issues using the new Tableau View LWC, please open a case through Salesforce.
